"""
Animate_Image.py - Rigid Body Part Puppet Animation (Forward Kinematics)

This script handles the animation rendering pipeline:
1. Loads cached body part segmentations generated by segment_image.py.
2. Loads pre-generated motion sequences.
3. Applies Forward Kinematics (FK) and perspective warping to animate the puppet.
4. Overlays the motion skeleton on top and saves the result as an animated GIF.

This script is completely independent of training and model inference.
"""

from ActionConditionedLSTM.config import IOFILES_DIR
import os
import math
import cv2
import numpy as np
import imageio
import pickle
from tqdm import tqdm

from ActionConditionedLSTM.config import (
    TARGET_IMAGE_PATH, GENERATED_MOTION_PATH, ANIMATED_CHARACTER_PATH,
    TORSO_EXPANSION_FACTOR, LIMB_OVERLAP_FACTOR, SKELETON_BONES,
    OVERLAP_SKELETON
)


# =============================================================================
# 1. Canvas Compositing & Forward Kinematics (FK) Rendering
# =============================================================================

def blend_onto_canvas(canvas: np.ndarray, patch: np.ndarray, tx: int, ty: int):
    """
    Alpha-blends an RGBA patch onto a 3-channel BGR canvas at top-left pixel offset (tx, ty).
    """
    ch, cw = canvas.shape[:2]
    rh, rw = patch.shape[:2]
    
    src_x1, src_y1 = max(0, -tx), max(0, -ty)
    dst_x1, dst_y1 = max(0, tx), max(0, ty)
    src_x2, src_y2 = min(rw, cw - tx), min(rh, ch - ty)
    dst_x2, dst_y2 = dst_x1 + (src_x2 - src_x1), dst_y1 + (src_y2 - src_y1)
    
    if src_x2 <= src_x1 or src_y2 <= src_y1:
        return
    
    region = patch[src_y1:src_y2, src_x1:src_x2]
    alpha = region[:, :, 3:4].astype(float) / 255.0
    canvas[dst_y1:dst_y2, dst_x1:dst_x2, :3] = (
        alpha * region[:, :, :3] + (1.0 - alpha) * canvas[dst_y1:dst_y2, dst_x1:dst_x2, :3]
    ).astype(np.uint8)


def warp_quad_onto_canvas(canvas: np.ndarray, patch_rgba: np.ndarray, src_quad: list, dst_quad: list):
    """
    Warps patch_rgba using a 4-point perspective transform mapping src_quad 
    (L_Sho, R_Sho, R_Hip, L_Hip) directly onto dst_quad in canvas space.
    """
    h, w = canvas.shape[:2]
    src_pts = np.float32(src_quad)
    dst_pts = np.float32(dst_quad)
    
    M = cv2.getPerspectiveTransform(src_pts, dst_pts)
    warped_rgba = cv2.warpPerspective(
        patch_rgba, M, (w, h),
        flags=cv2.INTER_LINEAR,
        borderMode=cv2.BORDER_CONSTANT,
        borderValue=(0, 0, 0, 0)
    )
    
    alpha = warped_rgba[:, :, 3:4].astype(float) / 255.0
    canvas[:, :, :3] = (
        alpha * warped_rgba[:, :, :3] + (1.0 - alpha) * canvas[:, :, :3]
    ).astype(np.uint8)


def place_and_rotate_limb(canvas: np.ndarray, patch_rgba: np.ndarray, p1_patch: np.ndarray, 
                           p2_patch: np.ndarray, target_p1: np.ndarray, target_p2: np.ndarray):
    """
    Rotates and scales a limb patch to align vector (p1_patch -> p2_patch) with 
    target vector (target_p1 -> target_p2), then blends it onto canvas.
    """
    v_src = p2_patch - p1_patch
    L_src = np.linalg.norm(v_src)
    if L_src < 1e-3: 
        return
    angle_src = math.degrees(math.atan2(v_src[1], v_src[0]))
    
    v_dst = target_p2 - target_p1
    L_dst = np.linalg.norm(v_dst)
    if L_dst < 1e-3: 
        return
    angle_dst = math.degrees(math.atan2(v_dst[1], v_dst[0]))
    
    # Scale factor with a boost to ensure limb joint overlap
    scale = np.clip((L_dst / L_src) * LIMB_OVERLAP_FACTOR, 0.4, 2.3)
    
    # In OpenCV (Y down), rotation angle is -(angle_dst - angle_src)
    opencv_angle = -(angle_dst - angle_src)
    
    ph, pw = patch_rgba.shape[:2]
    M = cv2.getRotationMatrix2D((float(p1_patch[0]), float(p1_patch[1])), opencv_angle, scale)
    
    cos_a, sin_a = abs(M[0, 0]), abs(M[0, 1])
    new_w = int(ph * sin_a + pw * cos_a)
    new_h = int(ph * cos_a + pw * sin_a)
    
    M[0, 2] += (new_w - pw) / 2.0
    M[1, 2] += (new_h - ph) / 2.0
    
    rotated = cv2.warpAffine(
        patch_rgba, M, (new_w, new_h),
        flags=cv2.INTER_LINEAR,
        borderMode=cv2.BORDER_CONSTANT,
        borderValue=(0, 0, 0, 0)
    )
    
    p1_new = M @ np.array([p1_patch[0], p1_patch[1], 1.0])
    tx = int(target_p1[0] - p1_new[0])
    ty = int(target_p1[1] - p1_new[1])
    
    blend_onto_canvas(canvas, rotated, tx, ty)


def render_fk_frame(canvas: np.ndarray, parts: dict, frame_kpts: np.ndarray):
    """
    Renders all character body parts onto canvas for a single animation frame 
    using Forward Kinematics (FK) and Z-order compositing.
    """
    def draw_limb(name, j1, j2):
        if name not in parts: 
            return
        part = parts[name]
        t1 = frame_kpts[j1].copy()
        t2 = frame_kpts[j2].copy()
        place_and_rotate_limb(canvas, part['patch'], part['p1'], part['p2'], t1, t2)

    # 1. Back Legs (R_Hip = 8)
    draw_limb('R_upper_leg', 8, 10)
    draw_limb('R_lower_leg', 10, 12)
    
    # 2. Torso (Perspective Quad anchored at Shoulders 1,2 and Hips 8,7)
    if 'torso' in parts:
        part = parts['torso']
        src_quad = [
            part['joints']['L_Sho'], part['joints']['R_Sho'],
            part['joints']['R_Hip'], part['joints']['L_Hip']
        ]
        dst_quad = [frame_kpts[1], frame_kpts[2], frame_kpts[8], frame_kpts[7]]
        
        # Outward expansion of torso quad to seamlessly overlap shoulders and hips
        dst_pts = np.float32(dst_quad)
        center_pts = np.mean(dst_pts, axis=0)
        dst_pts_expanded = center_pts + (dst_pts - center_pts) * TORSO_EXPANSION_FACTOR
        
        warp_quad_onto_canvas(canvas, part['patch'], src_quad, dst_pts_expanded)

    # 3. Front Legs (L_Hip = 7)
    draw_limb('L_upper_leg', 7, 9)
    draw_limb('L_lower_leg', 9, 11)

    # 4. Face (Face = 0)
    if 'face' in parts:
        part = parts['face']
        target_face = frame_kpts[0]
        place_and_rotate_limb(canvas, part['patch'], part['center'], 
                              part['center'] + np.array([0, 1]), 
                              target_face, target_face + np.array([0, 1]))

    # 5. Upper Arms (R_Sho = 2, L_Sho = 1)
    draw_limb('R_upper_arm', 2, 4)
    draw_limb('L_upper_arm', 1, 3)

    # 6. Lower Arms
    draw_limb('R_lower_arm', 4, 6)
    draw_limb('L_lower_arm', 3, 5)


# =============================================================================
# 2. Motion Denormalization
# =============================================================================

def denormalize_points(generated_seq: np.ndarray, source_kpts: np.ndarray) -> np.ndarray:
    """
    Denormalizes 2D motion keypoints back to canvas pixel coordinates using 
    the character's torso length and hip position.
    """
    hip_mid = (source_kpts[7] + source_kpts[8]) / 2.0
    torso_length = np.linalg.norm((source_kpts[1] + source_kpts[2]) / 2.0 - hip_mid)
    
    denorm = np.copy(generated_seq)
    for i in range(len(denorm)):
        denorm[i, :, 1] = -denorm[i, :, 1] # Un-flip Y coordinate
        denorm[i] = denorm[i] * torso_length + hip_mid
    return denorm


# =============================================================================
# 3. Main Pipeline Execution
# =============================================================================

def main():
    iofiles_dir = IOFILES_DIR
    target_image = TARGET_IMAGE_PATH
    base_name = os.path.splitext(os.path.basename(target_image))[0]
    segmentation_cache = os.path.join(iofiles_dir, f"{base_name}_segmentation.pkl")
    
    # 1. Load cached segmentation data
    if not os.path.exists(segmentation_cache):
        raise FileNotFoundError(
            f"Segmentation cache not found at: {segmentation_cache}\n"
            "Please run 'python segment_image.py' first to perform and cache the image segmentation."
        )
        
    print(f"Loading cached segmentation from {segmentation_cache}...")
    with open(segmentation_cache, 'rb') as f:
        cache_data = pickle.load(f)
        
    parts = cache_data['parts']
    source_kpts = cache_data['source_kpts']
    
    # 2. Load target image to determine rendering dimensions
    img = cv2.imread(target_image)
    if img is None:
        raise ValueError(f"Could not read target image to determine dimensions: {target_image}")
    h, w = img.shape[:2]
    
    # 3. Load pre-generated motion sequence
    motion_path = GENERATED_MOTION_PATH
    if not os.path.exists(motion_path):
        raise FileNotFoundError(f"Pre-generated motion file not found at {motion_path}")
        
    print(f"Loading pre-generated motion from {motion_path}...")
    raw_motion = np.load(motion_path)
    if raw_motion.ndim == 2 and raw_motion.shape[1] == 26:
        raw_motion = raw_motion.reshape(-1, 13, 2)
        
    denorm_motion = denormalize_points(raw_motion, source_kpts)
    
    frames = []
    
    # Bone connections for skeleton overlay visualization
    skeleton_bones = SKELETON_BONES
    
    for i, frame_kpts in enumerate(tqdm(denorm_motion, desc="Rendering animation")):
        canvas = np.ones((h, w, 3), dtype=np.uint8) * 255
        
        # 1. Render character puppet via FK
        render_fk_frame(canvas, parts, frame_kpts)
        
        # 2. Overlay skeleton lines on top (if enabled in config)
        if OVERLAP_SKELETON:
            for (start_idx, end_idx) in skeleton_bones:
                pt1 = tuple(frame_kpts[start_idx].astype(int))
                pt2 = tuple(frame_kpts[end_idx].astype(int))
                cv2.line(canvas, pt1, pt2, (0, 0, 255), 3) # Red bones
                
            for pt_idx, pt in enumerate(frame_kpts):
                center = tuple(pt.astype(int))
                color = (255, 255, 0) if pt_idx == 0 else (0, 255, 0) # Cyan head, Green joints
                cv2.circle(canvas, center, 5, color, -1)
            
        frames.append(canvas)
        
    output_gif = ANIMATED_CHARACTER_PATH
    imageio.mimsave(output_gif, frames, fps=15, loop=0)
    print(f"Done! Animation saved to {output_gif}")


if __name__ == "__main__":
    main()
